/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 16-Nov-2021 6:45:27 PM 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0 
;

/* Drop Tables */

DROP TABLE IF EXISTS `CuentaPersonal` CASCADE
;

DROP TABLE IF EXISTS `Hashtag` CASCADE
;

DROP TABLE IF EXISTS `Moderador` CASCADE
;

DROP TABLE IF EXISTS `Seguidor` CASCADE
;

DROP TABLE IF EXISTS `Tageo` CASCADE
;

DROP TABLE IF EXISTS `Tweet` CASCADE
;

DROP TABLE IF EXISTS `Usuario` CASCADE
;

/* Create Tables */

CREATE TABLE `CuentaPersonal`
(
	`idCuentaPersonal` INT NOT NULL,
	`idUsuario` INT NOT NULL,
	CONSTRAINT `PK_CuentaPersonal` PRIMARY KEY (`idCuentaPersonal` ASC)
)

;

CREATE TABLE `Hashtag`
(
	`nombre` VARCHAR(50) NOT NULL,
	CONSTRAINT `PK_Hashtag` PRIMARY KEY (`nombre` ASC)
)

;

CREATE TABLE `Moderador`
(
	`idModerador` INT NOT NULL AUTO_INCREMENT,
	`idUsuario` INT NOT NULL,
	CONSTRAINT `PK_Moderador` PRIMARY KEY (`idModerador` ASC)
)

;

CREATE TABLE `Seguidor`
(
	`idSeguidor` INT NOT NULL,
	`idUsuario` INT NOT NULL,
	CONSTRAINT `PK_Seguidor` PRIMARY KEY (`idSeguidor` ASC, `idUsuario` ASC)
)

;

CREATE TABLE `Tageo`
(
	`idTag` INT NOT NULL,
	`idTweet` INT NULL,
	`nombre` VARCHAR(50) NULL,
	CONSTRAINT `PK_Tageo` PRIMARY KEY (`idTag` ASC)
)

;

CREATE TABLE `Tweet`
(
	`idTweet` INT NOT NULL,
	`cuerpo` VARCHAR(50) NOT NULL,
	`fechaPublicacion` DATE NOT NULL,
	`horaPublicacion` TIME NOT NULL,
	`multimedia` BLOB NULL,
	`likes` INT NOT NULL,
	`idModerador` INT NULL,
	`idCuentaPersonal` INT NULL,
	CONSTRAINT `PK_Tweet` PRIMARY KEY (`idTweet` ASC)
)

;

CREATE TABLE `Usuario`
(
	`idUsuario` INT NOT NULL,
	`fotoPerfil` BLOB NOT NULL,
	`nombre` VARCHAR(50) NOT NULL,
	`apellidoPaterno` VARCHAR(50) NOT NULL,
	`apellidoMaterno` VARCHAR(50) NOT NULL,
	`fechaNacimiento` DATE NOT NULL,
	`email` VARCHAR(50) NOT NULL,
	`nombreUsuario` VARCHAR(50) NOT NULL,
	`password` VARCHAR(50) NOT NULL,
	CONSTRAINT `PK_Usuario` PRIMARY KEY (`idUsuario` ASC)
)

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `CuentaPersonal` 
 ADD INDEX `IXFK_CuentaPersonal_Usuario` (`idUsuario` ASC)
;

ALTER TABLE `Moderador` 
 ADD INDEX `IXFK_Moderador_Usuario` (`idUsuario` ASC)
;

ALTER TABLE `Seguidor` 
 ADD INDEX `IXFK_Seguidor` (`idSeguidor` ASC)
;

ALTER TABLE `Seguidor` 
 ADD INDEX `IXFK_Usuario` (`idUsuario` ASC)
;

ALTER TABLE `Tageo` 
 ADD INDEX `IXFK_Tageo_Hashtag` (`nombre` ASC)
;

ALTER TABLE `Tageo` 
 ADD INDEX `IXFK_Tageo_Tweet` (`idTweet` ASC)
;

ALTER TABLE `Tweet` 
 ADD INDEX `IXFK_Tweet_CuentaPersonal` (`idCuentaPersonal` ASC)
;

ALTER TABLE `Tweet` 
 ADD INDEX `IXFK_Tweet_Moderador` (`idModerador` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `CuentaPersonal` 
 ADD CONSTRAINT `FK_CuentaPersonal_Usuario`
	FOREIGN KEY (`idUsuario`) REFERENCES `Usuario` (`idUsuario`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Moderador` 
 ADD CONSTRAINT `FK_Moderador_Usuario`
	FOREIGN KEY (`idUsuario`) REFERENCES `Usuario` (`idUsuario`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Seguidor` 
 ADD CONSTRAINT `FK_Seguidor`
	FOREIGN KEY (`idSeguidor`) REFERENCES `Usuario` (`idUsuario`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Seguidor` 
 ADD CONSTRAINT `FK_Usuario`
	FOREIGN KEY (`idUsuario`) REFERENCES `Usuario` (`idUsuario`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Tageo` 
 ADD CONSTRAINT `FK_Tageo_Hashtag`
	FOREIGN KEY (`nombre`) REFERENCES `Hashtag` (`nombre`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Tageo` 
 ADD CONSTRAINT `FK_Tageo_Tweet`
	FOREIGN KEY (`idTweet`) REFERENCES `Tweet` (`idTweet`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Tweet` 
 ADD CONSTRAINT `FK_Tweet_CuentaPersonal`
	FOREIGN KEY (`idCuentaPersonal`) REFERENCES `CuentaPersonal` (`idCuentaPersonal`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Tweet` 
 ADD CONSTRAINT `FK_Tweet_Moderador`
	FOREIGN KEY (`idModerador`) REFERENCES `Moderador` (`idModerador`) ON DELETE Restrict ON UPDATE Restrict
;

SET FOREIGN_KEY_CHECKS=1 
;
